K1 = csvread('D:/Study/Bioinformatics/QSP/ncbi/datasets/Kernel_matrix/AvBlock/KM_gaussian_AvBlock_train391.csv');
K2 = csvread('D:/Study/Bioinformatics/QSP/ncbi/datasets/Kernel_matrix/PSSM_DCT/KM_gaussian_PSSM_DCT_train391.csv');
K3 = csvread('D:/Study/Bioinformatics/QSP/ncbi/datasets/Kernel_matrix/PSSM_DWT/KM_gaussian_PSSM_DWT_train391.csv');
K4 = csvread('D:/Study/Bioinformatics/QSP/ncbi/datasets/Kernel_matrix/PSSM_Pse/KM_gaussian_PSSM_Pse_train391.csv');
Kernels_list = cat(3, K1, K2, K3, K4);
adjmat = csvread('D:/Study/Bioinformatics/QSP/ncbi/datasets/train391_label.csv');
dim = 1;
regcoef1 = 0.01;
regcoef2 = 0.001;
[weight_v] = hsic_kernel_weights_norm(Kernels_list,adjmat,dim,regcoef1,regcoef2)